import React from 'react';

function formatDate(d) {
  try {
    return new Date(d).toLocaleString();
  } catch (e) {
    return d || '—';
  }
}

function buildExplorerTxUrl(txHash, network) {
  const isMainnet = network === 'mainnet';
  return isMainnet
    ? `https://stellar.expert/explorer/public/tx/${txHash}`
    : `https://stellar.expert/explorer/testnet/tx/${txHash}`;
}

// Opens a new window with the receipt HTML and triggers print (user can choose "Save as PDF").
export function openReceiptWindow({ escrow, network }) {
  const w = window.open('', '_blank', 'noopener,noreferrer');
  if (!w) return;

  const parts = [];
  parts.push('<!doctype html><html><head><meta charset="utf-8">');
  parts.push('<meta name="viewport" content="width=device-width,initial-scale=1">');
  parts.push('<title>Escrow Receipt</title>');

  // Minimal, professional styles optimized for print
  parts.push(`<style>
    :root{color-scheme:dark light}
    body{font-family:Inter, -apple-system, system-ui, "Segoe UI", Roboto, "Helvetica Neue", Arial; margin:24px; color:#111}
    .container{max-width:800px;margin:0 auto}
    .header{display:flex;justify-content:space-between;align-items:center}
    h1{font-size:20px;margin:0}
    .muted{color:#6b7280}
    .card{border:1px solid #e5e7eb;padding:16px;border-radius:6px;margin-top:12px}
    .grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}
    .row{display:flex;justify-content:space-between}
    table{width:100%;border-collapse:collapse;margin-top:8px}
    th,td{padding:8px;border-bottom:1px solid #e5e7eb;text-align:left;font-size:13px}
    a{color:#0f172a}
    @media print{body{margin:12mm} .no-print{display:none!important}}
  </style>`);

  parts.push('</head><body><div class="container">');

  parts.push('<div class="header">');
  parts.push(`<div><h1>Escrow Receipt</h1><div class="muted">Documentary evidence for escrow transaction</div></div>`);
  parts.push(`<div class="muted">Generated: ${formatDate(new Date())}</div>`);
  parts.push('</div>');

  parts.push('<div class="card">');
  parts.push(`<div class="grid">`);
  parts.push(`<div><p class="muted">Escrow ID</p><strong>#${escrow.id}</strong></div>`);
  parts.push(`<div><p class="muted">Status</p><strong>${escrow.status || '—'}</strong></div>`);
  parts.push(`</div>`);

  parts.push('<div style="margin-top:12px">');
  parts.push(`<p class="muted">Title</p><div><strong>${escrow.title || '—'}</strong></div>`);
  parts.push('</div>');

  parts.push('<div class="grid" style="margin-top:12px">');
  parts.push(`<div><p class="muted">Client</p><div><strong>${escrow.clientName || escrow.clientAddress || '—'}</strong><div class="muted">${escrow.clientAddress || ''}</div></div></div>`);
  parts.push(`<div><p class="muted">Freelancer</p><div><strong>${escrow.freelancerName || escrow.freelancerAddress || '—'}</strong><div class="muted">${escrow.freelancerAddress || ''}</div></div></div>`);
  parts.push(`</div>`);

  parts.push('<div class="grid" style="margin-top:12px">');
  parts.push(`<div><p class="muted">Amount</p><strong>${escrow.totalAmount || '—'}</strong></div>`);
  parts.push(`<div><p class="muted">Remaining</p><strong>${escrow.remainingBalance || '—'}</strong></div>`);
  parts.push(`</div>`);

  parts.push('<div class="grid" style="margin-top:12px">');
  parts.push(`<div><p class="muted">Created</p><strong>${formatDate(escrow.createdAt)}</strong></div>`);
  parts.push(`<div><p class="muted">Release / Deadline</p><strong>${formatDate(escrow.deadline)}</strong></div>`);
  parts.push(`</div>`);

  // Transaction hashes
  parts.push('<div style="margin-top:14px">');
  parts.push('<p class="muted">Transactions</p>');
  parts.push('<table><thead><tr><th>Role</th><th>Hash</th><th>Explorer</th></tr></thead><tbody>');

  if (escrow.transactionHash) {
    const url = buildExplorerTxUrl(escrow.transactionHash, network);
    parts.push(`<tr><td>Main Escrow</td><td>${escrow.transactionHash}</td><td><a href="${url}" target="_blank" rel="noopener">View</a></td></tr>`);
  }

  if (Array.isArray(escrow.milestones)) {
    escrow.milestones.forEach((m, i) => {
      if (m.txHash) {
        const url = buildExplorerTxUrl(m.txHash, network);
        parts.push(`<tr><td>Milestone ${i}: ${m.title || ''}</td><td>${m.txHash}</td><td><a href="${url}" target="_blank" rel="noopener">View</a></td></tr>`);
      }
    });
  }

  parts.push('</tbody></table>');
  parts.push('</div>');

  // Agreed terms / description
  if (escrow.terms || escrow.description) {
    parts.push('<div style="margin-top:14px">');
    parts.push('<p class="muted">Agreed Terms</p>');
    parts.push(`<div>${(escrow.terms || escrow.description).replace(/\n/g, '<br/>')}</div>`);
    parts.push('</div>');
  }

  // Footer
  parts.push('<div style="margin-top:24px;font-size:12px;color:#6b7280">');
  parts.push('This receipt was generated by Stellar Trust Escrow and may be used as documentary evidence of the escrow transaction.');
  parts.push('</div>');

  parts.push('</div>'); // card
  parts.push('</div></body></html>');

  w.document.write(parts.join('\n'));
  w.document.close();

  // Wait briefly for resources to load, then trigger print.
  setTimeout(() => {
    try {
      w.focus();
      w.print();
      // Do not auto-close — let user keep the window if they want.
    } catch (e) {
      // ignore
    }
  }, 250);
}

export default function EscrowReceipt() {
  return null; // This component is a helper and has no in-DOM UI
}
